/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Configurador;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Idrovo
 */
public class Inicio extends javax.swing.JFrame {

    private Sesion inicioSesion;
    private VistaDivorcio vistaDivorcio;
    private VistaMatrimonio vistaMatrimonio;
    private VistaPersona vistaPersona;

    public Inicio() {
        initComponents();
        //CREAR VISTAS
        inicioSesion = new Sesion();
        vistaDivorcio = new VistaDivorcio();
        vistaMatrimonio = new VistaMatrimonio();
        vistaPersona = new VistaPersona();

        //Agregar Panel
        desktopPane.add(inicioSesion);
        desktopPane.add(vistaDivorcio);
        desktopPane.add(vistaMatrimonio);
        desktopPane.add(vistaPersona);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        flInicioSesion = new javax.swing.JMenu();
        flMatrimonio = new javax.swing.JMenu();
        flDivorcio = new javax.swing.JMenu();
        flRegistrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        flInicioSesion.setMnemonic('f');
        flInicioSesion.setText("INICIAR SESION");
        flInicioSesion.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                flInicioSesionMenuSelected(evt);
            }
        });
        menuBar.add(flInicioSesion);

        flMatrimonio.setMnemonic('e');
        flMatrimonio.setText("MATRIMONIO");
        flMatrimonio.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                flMatrimonioMenuSelected(evt);
            }
        });
        menuBar.add(flMatrimonio);

        flDivorcio.setMnemonic('h');
        flDivorcio.setText("DIVORCIO");
        flDivorcio.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                flDivorcioMenuSelected(evt);
            }
        });
        menuBar.add(flDivorcio);

        flRegistrar.setMnemonic('h');
        flRegistrar.setText("REGISTAR");
        flRegistrar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                flRegistrarMenuSelected(evt);
            }
        });
        flRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flRegistrarMouseClicked(evt);
            }
        });
        menuBar.add(flRegistrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flRegistrarMouseClicked
        ocultar();
        Configurador c = Configurador.getConfigurador(0);
        if (c.getId() != 0) {
            vistaPersona.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA INICIADO SESION", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_flRegistrarMouseClicked

    private void flMatrimonioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_flMatrimonioMenuSelected
        ocultar();
        Configurador c = Configurador.getConfigurador(0);
        if (c.getId() != 0) {
            vistaMatrimonio.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA INICIADO SESION", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_flMatrimonioMenuSelected

    private void flDivorcioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_flDivorcioMenuSelected
        ocultar();
        Configurador c = Configurador.getConfigurador(0);
        if (c.getId() != 0) {
            vistaDivorcio.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA INICIADO SESION", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_flDivorcioMenuSelected

    private void flRegistrarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_flRegistrarMenuSelected
        ocultar();
        Configurador c = Configurador.getConfigurador(0);
        if (c.getId() != 0) {
            vistaPersona.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO SE HA INICIADO SESION", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_flRegistrarMenuSelected

    private void flInicioSesionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_flInicioSesionMenuSelected
        ocultar();
        inicioSesion.setVisible(true);
    }//GEN-LAST:event_flInicioSesionMenuSelected

    private void ocultar() {
        inicioSesion.setVisible(false);
        vistaDivorcio.setVisible(false);
        vistaMatrimonio.setVisible(false);
        vistaPersona.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu flDivorcio;
    private javax.swing.JMenu flInicioSesion;
    private javax.swing.JMenu flMatrimonio;
    private javax.swing.JMenu flRegistrar;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
