/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorMatrimonio;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Matrimonio;
import ec.edu.ups.modelo.Persona;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul Idrovo
 */
public class VistaDivorcio extends javax.swing.JInternalFrame {

    private ControladorMatrimonio controladorMatrimonio;
    private ControladorPersona controladorPersona;

    public VistaDivorcio() {
        initComponents();
        controladorMatrimonio = new ControladorMatrimonio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatrimonios = new javax.swing.JTable();
        btnDivorciar = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        tblMatrimonios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "COMPROMETIDO1", "COMPROMETIDO2", "TESTIGO1", "TESTIGO2", "JUEZ", "FECHA", "LUGAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMatrimonios);

        btnDivorciar.setText("DIVORCIAR");
        btnDivorciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivorciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(btnDivorciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnDivorciar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        lista();
    }//GEN-LAST:event_formFocusGained
    public void lista() {
        List<Matrimonio> lstMatrimonios = controladorMatrimonio.listaMatrimonios();

        DefaultTableModel modelo = (DefaultTableModel) tblMatrimonios.getModel();
        modelo.setRowCount(0);
        tblMatrimonios.setModel(modelo);
        Object[] fila = new Object[8];

        for (Matrimonio DatoMatrimonio : lstMatrimonios) {
            //controladorPersona
            Persona pr = new Persona();
            fila[0] = DatoMatrimonio.getId();
            pr = controladorPersona.readId(DatoMatrimonio.getComprometido1Id());
            fila[1] = pr.getNombre() + " " + pr.getApellido();
            pr = controladorPersona.readId(DatoMatrimonio.getComprometido2Id());
            fila[2] = pr.getNombre() + " " + pr.getApellido();
            pr = controladorPersona.readId(DatoMatrimonio.getTestigo1Id());
            fila[3] = pr.getNombre() + " " + pr.getApellido();
            pr = controladorPersona.readId(DatoMatrimonio.getTestigo2Id());
            fila[4] = pr.getNombre() + " " + pr.getApellido();
            pr = controladorPersona.readId(DatoMatrimonio.getJuezId());
            fila[5] = pr.getNombre() + " " + pr.getApellido();
            fila[6] = DatoMatrimonio.getFecha();
            fila[7] = DatoMatrimonio.getLugar();
            modelo.addRow(fila);
        }
        this.tblMatrimonios.setModel(modelo);
    }
    private void btnDivorciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivorciarActionPerformed
        int fila = tblMatrimonios.getSelectedRow();
        int id = Integer.parseInt(tblMatrimonios.getValueAt(fila, 0).toString());
        controladorMatrimonio.update(id);
        id = Integer.parseInt(tblMatrimonios.getValueAt(fila, 1).toString());
        Persona pr = new Persona(id, true);
        controladorPersona.update(pr);
        id = Integer.parseInt(tblMatrimonios.getValueAt(fila, 2).toString());
        pr = new Persona(id, true);
        controladorPersona.update(pr);
        lista();
    }//GEN-LAST:event_btnDivorciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivorciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMatrimonios;
    // End of variables declaration//GEN-END:variables
}
