/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorMatrimonio;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Matrimonio;
import ec.edu.ups.modelo.Persona;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Idrovo
 */
public class VistaMatrimonio extends javax.swing.JInternalFrame {

    ControladorPersona personaCtrl;
    ControladorMatrimonio matrimonioCtrl;

    public VistaMatrimonio() {
        initComponents();
        personaCtrl = new ControladorPersona();
        matrimonioCtrl=new ControladorMatrimonio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdComprometido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaComprometido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreComprometido1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoComprometido1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionComprometido1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbGeneroComprometido1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtFechaNacimientoComprometido1 = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtIdComprometido2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtCedulaComprometido2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtNombreComprometido2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtApellidoComprometido2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtDireccionComprometido2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        cmbGeneroComprometido2 = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        txtFechaNacimientoComprometido2 = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        txtIdTestigo2 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        txtCedulaTestigo2 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txtNombreTestigo2 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txtApellidoTestigo2 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        txtDireccionTestigo2 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        cmbGeneroTestigo2 = new javax.swing.JComboBox<>();
        jLabel82 = new javax.swing.JLabel();
        txtFechaNacimientoTestigo2 = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        txtIdTestigo1 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        txtCedulaTestigo1 = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        txtNombreTestigo1 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        txtApellidoTestigo1 = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        txtDireccionTestigo1 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        cmbGeneroTestigo1 = new javax.swing.JComboBox<>();
        jLabel89 = new javax.swing.JLabel();
        txtFechaNacimientoTestigo1 = new javax.swing.JFormattedTextField();
        btnRegistar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("COMPROMETIDO 1"));

        jLabel2.setText("ID");

        txtIdComprometido1.setEnabled(false);

        jLabel3.setText("CEDULA");

        txtCedulaComprometido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaComprometido1KeyTyped(evt);
            }
        });

        jLabel4.setText("NOMBRE");

        txtNombreComprometido1.setEnabled(false);

        jLabel5.setText("APELLIDO");

        txtApellidoComprometido1.setEnabled(false);

        jLabel6.setText("DIRECCION");

        txtDireccionComprometido1.setEnabled(false);

        jLabel7.setText("GENERO");

        cmbGeneroComprometido1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GENERO", "MASCULINO", "FEMENINO" }));
        cmbGeneroComprometido1.setEnabled(false);

        jLabel8.setText("F. NACIMIENTO");

        txtFechaNacimientoComprometido1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionComprometido1)
                            .addComponent(cmbGeneroComprometido1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNacimientoComprometido1)
                                    .addComponent(txtApellidoComprometido1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdComprometido1)
                                    .addComponent(txtCedulaComprometido1)
                                    .addComponent(txtNombreComprometido1))))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedulaComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidoComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaNacimientoComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccionComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbGeneroComprometido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("COMPROMETIDO 2"));

        jLabel30.setText("ID");

        txtIdComprometido2.setEnabled(false);

        jLabel31.setText("CEDULA");

        txtCedulaComprometido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaComprometido2KeyTyped(evt);
            }
        });

        jLabel38.setText("NOMBRE");

        txtNombreComprometido2.setEnabled(false);

        jLabel39.setText("APELLIDO");

        txtApellidoComprometido2.setEnabled(false);

        jLabel40.setText("DIRECCION");

        txtDireccionComprometido2.setEnabled(false);

        jLabel41.setText("GENERO");

        cmbGeneroComprometido2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GENERO", "MASCULINO", "FEMENINO" }));
        cmbGeneroComprometido2.setEnabled(false);

        jLabel42.setText("F. NACIMIENTO");

        txtFechaNacimientoComprometido2.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionComprometido2)
                            .addComponent(cmbGeneroComprometido2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(34, 34, 34)
                                .addComponent(txtNombreComprometido2))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNacimientoComprometido2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtApellidoComprometido2)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedulaComprometido2)
                                    .addComponent(txtIdComprometido2))))))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtIdComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtCedulaComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtNombreComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtApellidoComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtFechaNacimientoComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtDireccionComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cmbGeneroComprometido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("TESTIGO 2"));

        jLabel76.setText("ID");

        txtIdTestigo2.setEnabled(false);

        jLabel77.setText("CEDULA");

        txtCedulaTestigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaTestigo2KeyTyped(evt);
            }
        });

        jLabel78.setText("NOMBRE");

        txtNombreTestigo2.setEnabled(false);

        jLabel79.setText("APELLIDO");

        txtApellidoTestigo2.setEnabled(false);

        jLabel80.setText("DIRECCION");

        txtDireccionTestigo2.setEnabled(false);

        jLabel81.setText("GENERO");

        cmbGeneroTestigo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GENERO", "MASCULINO", "FEMENINO" }));
        cmbGeneroTestigo2.setEnabled(false);

        jLabel82.setText("F. NACIMIENTO");

        txtFechaNacimientoTestigo2.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel82)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel80)
                            .addComponent(jLabel81))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionTestigo2)
                            .addComponent(cmbGeneroTestigo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel79)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNacimientoTestigo2)
                                    .addComponent(txtApellidoTestigo2)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel76))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdTestigo2)
                                    .addComponent(txtCedulaTestigo2)
                                    .addComponent(txtNombreTestigo2))))))
                .addGap(15, 15, 15))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(txtIdTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(txtCedulaTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(txtNombreTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(txtApellidoTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(txtFechaNacimientoTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(txtDireccionTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(cmbGeneroTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("TESTIGO 1"));

        jLabel83.setText("ID");

        txtIdTestigo1.setEnabled(false);

        jLabel84.setText("CEDULA");

        txtCedulaTestigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaTestigo1KeyTyped(evt);
            }
        });

        jLabel85.setText("NOMBRE");

        txtNombreTestigo1.setEnabled(false);

        jLabel86.setText("APELLIDO");

        txtApellidoTestigo1.setEnabled(false);

        jLabel87.setText("DIRECCION");

        txtDireccionTestigo1.setEnabled(false);

        jLabel88.setText("GENERO");

        cmbGeneroTestigo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GENERO", "MASCULINO", "FEMENINO" }));
        cmbGeneroTestigo1.setEnabled(false);

        jLabel89.setText("F. NACIMIENTO");

        txtFechaNacimientoTestigo1.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel89)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel87)
                            .addComponent(jLabel88))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionTestigo1)
                            .addComponent(cmbGeneroTestigo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel86)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNacimientoTestigo1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtApellidoTestigo1)))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel85)
                                    .addComponent(jLabel84)
                                    .addComponent(jLabel83))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdTestigo1)
                                    .addComponent(txtCedulaTestigo1)
                                    .addComponent(txtNombreTestigo1))))))
                .addGap(15, 15, 15))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(txtIdTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(txtCedulaTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(txtNombreTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(txtApellidoTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(txtFechaNacimientoTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(txtDireccionTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(cmbGeneroTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnRegistar.setText("REGISTRAR");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        jLabel1.setText("LUGAR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLugar))
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnRegistar)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaComprometido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaComprometido1KeyTyped
        char validar = evt.getKeyChar();
        if (validar == '\n') {
            Persona persona = personaCtrl.buscarCedula(txtCedulaComprometido1.getText());
            if (persona != null) {
                if (persona.isEstadoCivil()) {
                    if (txtCedulaComprometido1.getText().equals(txtCedulaComprometido2.getText()) || txtCedulaComprometido1.getText().equals(txtCedulaTestigo1.getText())
                            || txtCedulaComprometido1.getText().equals(txtCedulaTestigo2.getText())) {
                        JOptionPane.showMessageDialog(null, "ESTA PERSONA SE ENCUENTRA EN LA LISTA DE LOS PARTICIPANTES", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                    } else {
                        txtIdComprometido1.setText(persona.getId() + "");
                        txtNombreComprometido1.setText(persona.getNombre());
                        txtApellidoComprometido1.setText(persona.getApellido());
                        txtFechaNacimientoComprometido1.setText(persona.getFechaNacimiento());
                        txtDireccionComprometido1.setText(persona.getDireccion());
                        if (persona.isGenero()) {
                            cmbGeneroComprometido1.setSelectedIndex(1);
                        } else {
                            cmbGeneroComprometido1.setSelectedIndex(2);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ESTA PERSONA YA ESTA EN UN MATRIMONIO", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "CEDULA NO EXISTE", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCedulaComprometido1KeyTyped

    private void txtCedulaComprometido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaComprometido2KeyTyped
        char validar = evt.getKeyChar();
        if (validar == '\n') {
            Persona persona = personaCtrl.buscarCedula(txtCedulaComprometido1.getText());
            if (persona != null) {
                if (persona.isEstadoCivil()) {
                    if (txtCedulaTestigo1.getText().equals(txtCedulaComprometido1.getText()) || txtCedulaTestigo1.getText().equals(txtCedulaComprometido2.getText())
                            || txtCedulaTestigo1.getText().equals(txtCedulaTestigo2.getText())) {
                        JOptionPane.showMessageDialog(null, "ESTA PERSONA SE ENCUENTRA EN LA LISTA DE LOS PARTICIPANTES", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                    } else {
                        txtIdComprometido1.setText(persona.getId() + "");
                        txtNombreComprometido1.setText(persona.getNombre());
                        txtApellidoComprometido1.setText(persona.getApellido());
                        txtFechaNacimientoComprometido1.setText(persona.getFechaNacimiento());
                        txtDireccionComprometido1.setText(persona.getDireccion());
                        if (persona.isGenero()) {
                            cmbGeneroComprometido1.setSelectedIndex(1);
                        } else {
                            cmbGeneroComprometido1.setSelectedIndex(2);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ESTA PERSONA YA ESTA EN UN MATRIMONIO", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "CEDULA NO EXISTE", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCedulaComprometido2KeyTyped

    private void txtCedulaTestigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaTestigo1KeyTyped
        char validar = evt.getKeyChar();
        if (validar == '\n') {
            Persona persona = personaCtrl.buscarCedula(txtCedulaComprometido1.getText());
            if (persona != null) {
                if (txtCedulaTestigo2.getText().equals(txtCedulaComprometido1.getText()) || txtCedulaTestigo2.getText().equals(txtCedulaComprometido2.getText())
                        || txtCedulaTestigo2.getText().equals(txtCedulaTestigo1.getText())) {
                    JOptionPane.showMessageDialog(null, "ESTA PERSONA SE ENCUENTRA EN LA LISTA DE LOS PARTICIPANTES", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                } else {
                    txtIdComprometido1.setText(persona.getId() + "");
                    txtNombreComprometido1.setText(persona.getNombre());
                    txtApellidoComprometido1.setText(persona.getApellido());
                    txtFechaNacimientoComprometido1.setText(persona.getFechaNacimiento());
                    txtDireccionComprometido1.setText(persona.getDireccion());
                    if (persona.isGenero()) {
                        cmbGeneroComprometido1.setSelectedIndex(1);
                    } else {
                        cmbGeneroComprometido1.setSelectedIndex(2);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "CEDULA NO EXISTE", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCedulaTestigo1KeyTyped

    private void txtCedulaTestigo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaTestigo2KeyTyped
        char validar = evt.getKeyChar();
        if (validar == '\n') {
            Persona persona = personaCtrl.buscarCedula(txtCedulaComprometido1.getText());
            if (persona != null) {
                if (txtCedulaTestigo2.getText().equals(txtCedulaComprometido1.getText()) || txtCedulaTestigo2.getText().equals(txtCedulaComprometido2.getText())
                        || txtCedulaTestigo2.getText().equals(txtCedulaTestigo1.getText())) {
                    JOptionPane.showMessageDialog(null, "ESTA PERSONA SE ENCUENTRA EN LA LISTA DE LOS PARTICIPANTES", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
                } else {
                    txtIdComprometido1.setText(persona.getId() + "");
                    txtNombreComprometido1.setText(persona.getNombre());
                    txtApellidoComprometido1.setText(persona.getApellido());
                    txtFechaNacimientoComprometido1.setText(persona.getFechaNacimiento());
                    txtDireccionComprometido1.setText(persona.getDireccion());
                    if (persona.isGenero()) {
                        cmbGeneroComprometido1.setSelectedIndex(1);
                    } else {
                        cmbGeneroComprometido1.setSelectedIndex(2);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "CEDULA NO EXISTE", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCedulaTestigo2KeyTyped

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        if (txtNombreComprometido1.getText().equals("") || txtNombreComprometido2.getText().equals("") || txtNombreTestigo1.getText().equals("")
                || txtNombreTestigo2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "EXISTEN CAMPOS VACIOS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        } else {
            Matrimonio matri = new Matrimonio();
            matri.setComprometido1Id(Integer.parseInt(txtIdComprometido1.getText()));
            matri.setComprometido2Id(Integer.parseInt(txtIdComprometido2.getText()));
            matri.setTestigo1Id(Integer.parseInt(txtIdTestigo1.getText()));
            matri.setTestigo2Id(Integer.parseInt(txtIdTestigo2.getText()));
            matri.setLugar(txtLugar.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = sdf.format(new Date());
            matri.setFecha(fecha);
            matrimonioCtrl.create(matri);
            personaCtrl.update(new Persona(Integer.parseInt(txtIdComprometido1.getText()), false));
            personaCtrl.update(new Persona(Integer.parseInt(txtIdComprometido2.getText()), false));
        }
    }//GEN-LAST:event_btnRegistarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<String> cmbGeneroComprometido1;
    private javax.swing.JComboBox<String> cmbGeneroComprometido2;
    private javax.swing.JComboBox<String> cmbGeneroTestigo1;
    private javax.swing.JComboBox<String> cmbGeneroTestigo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtApellidoComprometido1;
    private javax.swing.JTextField txtApellidoComprometido2;
    private javax.swing.JTextField txtApellidoTestigo1;
    private javax.swing.JTextField txtApellidoTestigo2;
    private javax.swing.JTextField txtCedulaComprometido1;
    private javax.swing.JTextField txtCedulaComprometido2;
    private javax.swing.JTextField txtCedulaTestigo1;
    private javax.swing.JTextField txtCedulaTestigo2;
    private javax.swing.JTextField txtDireccionComprometido1;
    private javax.swing.JTextField txtDireccionComprometido2;
    private javax.swing.JTextField txtDireccionTestigo1;
    private javax.swing.JTextField txtDireccionTestigo2;
    private javax.swing.JFormattedTextField txtFechaNacimientoComprometido1;
    private javax.swing.JFormattedTextField txtFechaNacimientoComprometido2;
    private javax.swing.JFormattedTextField txtFechaNacimientoTestigo1;
    private javax.swing.JFormattedTextField txtFechaNacimientoTestigo2;
    private javax.swing.JTextField txtIdComprometido1;
    private javax.swing.JTextField txtIdComprometido2;
    private javax.swing.JTextField txtIdTestigo1;
    private javax.swing.JTextField txtIdTestigo2;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombreComprometido1;
    private javax.swing.JTextField txtNombreComprometido2;
    private javax.swing.JTextField txtNombreTestigo1;
    private javax.swing.JTextField txtNombreTestigo2;
    // End of variables declaration//GEN-END:variables
}
